services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile         # FastAPI Dockerfile path
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - quadrant
    environment:
      DATABASE_URL: "postgresql://admin:root@postgres:5432/mlbooks_db"

  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit  # Streamlit Dockerfile path
    ports:
      - "8501:8501"
    depends_on:
      - api

  quadrant:
    build:
      context: ..
      dockerfile: docker/quadrant.Dockerfile  # Quadrant Dockerfile path
    ports:
      - "6333:6333"

  postgres:
    image: postgres:13
    hostname: localhost
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mlbooks_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: