# Dockerfile for Streamlit
FROM python:3.10-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements/streamlit.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Streamlit code into the container
COPY streamlit/ /app/

# Expose the port Streamlit will run on
EXPOSE 8501

# Run the Streamlit app
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
